export const squads: Record<string, string[]> = {
  'Spain': [
    'Unai Simón', 'David Raya', 'Alex Remiro',
    'Dani Carvajal', 'Alejandro Balde', 'Aymeric Laporte', 'Robin Le Normand', 'Nacho', 'Pau Cubarsí',
    'Pedri', 'Gavi', 'Rodri', 'Fabián Ruiz', 'Dani Olmo', 'Mikel Merino', 'Martín Zubimendi',
    'Lamine Yamal', 'Nico Williams', 'Álvaro Morata', 'Ayoze Pérez', 'Ferran Torres', 'Joselu', 'Bryan Gil',
  ],
  'Cabo Verde': [
    'Josimar Vozinha', 'Carlos Baptista',
    'Steven Fortes', 'Fernando Varela', 'Diogo Lopes', 'Willy Semedo', 'Kenny Rocha Santos',
    'Patrick Andrade', 'Garry Rodrigues', 'Ryan Mendes', 'Gilson Benchimol', 'Jamiro Monteiro',
    'Elves Baldé', 'Julio Tavares', 'Dylan Tavares', 'Jorge Duarte', 'Lisandro',
  ],
  'Belgium': [
    'Koen Casteels', 'Simon Mignolet', 'Matz Sels',
    'Toby Alderweireld', 'Jan Vertonghen', 'Wout Faes', 'Timothy Castagne', 'Thomas Meunier', 'Brandon Mechele',
    'Kevin De Bruyne', 'Axel Witsel', 'Leander Dendoncker', 'Amadou Onana', 'Orel Mangala',
    'Romelu Lukaku', 'Dodi Lukebakio', 'Jérémy Doku', 'Loïs Openda', 'Johan Bakayoko',
    'Alexis Saelemaekers', 'Charles De Ketelaere', 'Yannick Carrasco',
  ],
  'Egypt': [
    'Mohamed El-Shennawy', 'Ahmed Abou Gabal', 'Ibrahim El-Shenawy',
    'Ahmed Hegazi', 'Mahmoud El-Wensh', 'Omar Gaber', 'Ayman Ashraf', 'Mohamed Abdelmonem', 'Ahmed Fattouh',
    'Tarek Hamed', 'Emam Ashour', 'Ahmed Sayed Zizou', 'Ramadan Sobhi', 'Mahmoud Kahraba', 'Trézéguet',
    'Mohamed Salah', 'Omar Marmoush', 'Mostafa Mohamed', 'Marwan Attia', 'Ibrahim Adel',
  ],
  'Saudi Arabia': [
    'Mohammed Al-Owais', 'Sultan Al-Ghannam', 'Yasser Al-Mosailem',
    'Saud Abdulhamid', 'Ali Al-Bulayhi', 'Mohammed Al-Burayk', 'Abdulelah Al-Amri', 'Hassan Al-Tambakti',
    'Salman Al-Faraj', 'Sami Al-Naji', 'Mohamed Kanno', 'Abdulrahman Al-Aboud', 'Mohammed Al-Qasem',
    'Salem Al-Dawsari', 'Ali Al-Hassan', 'Firas Al-Buraikan', 'Abdullah Radif', 'Hattan Bahbri',
    'Nasser Al-Dawsari', 'Muhammed Al-Sahafi',
  ],
  'Uruguay': [
    'Sergio Rochet', 'Fernando Muslera', 'Sebastián Sosa',
    'Sebastián Coates', 'José María Giménez', 'Ronald Araújo', 'Mathías Olivera', 'Matías Viña', 'Diego Godín',
    'Rodrigo Bentancur', 'Federico Valverde', 'Nicolás De La Cruz', 'Matías Vecino', 'Nahitan Nández',
    'Giorgian De Arrascaeta', 'Darwin Núñez', 'Luis Suárez', 'Facundo Torres', 'Brian Rodríguez',
    'Maximiliano Araújo', 'Jonathan Rodríguez',
  ],
  'IR Iran': [
    'Alireza Beiranvand', 'Hossein Hosseini', 'Amir Abedzadeh',
    'Shoja Khalilzadeh', 'Majid Hosseini', 'Ehsan Hajsafi', 'Morteza Pouraliganji', 'Ramin Rezaeian', 'Mohammad Mohebi',
    'Ali Gholizadeh', 'Saman Ghoddos', 'Mehdi Torabi', 'Vahid Amiri', 'Saeid Ezatolahi', 'Alireza Jahanbakhsh',
    'Sardar Azmoun', 'Mehdi Taremi', 'Karim Ansarifard', 'Allahyar Sayyadmanesh',
  ],
  'New Zealand': [
    'Stefan Marinovic', 'Oliver Sail', 'Michael Woud',
    'Winston Reid', 'Michael Boxall', 'Bill Tuiloma', 'Tim Payne', 'Liberato Cacace', 'Nando Pijnaker',
    'Clayton Lewis', 'Elijah Just', 'Ryan Thomas', 'Matthew Garbett', 'Alex Rufer',
    'Chris Wood', 'Kosta Barbarouses', 'Callan Elliot', 'Ben Waine', 'Matthew Ridenton',
  ],
  'France': [
    'Mike Maignan', 'Alban Lafont', 'Brice Samba',
    'Jules Koundé', 'Ibrahima Konaté', 'William Saliba', 'Lucas Hernández', 'Theo Hernandez', 'Benjamin Pavard',
    'Aurélien Tchouaméni', 'Adrien Rabiot', 'Eduardo Camavinga', 'Warren Zaïre-Emery', 'Mattéo Guendouzi',
    'Antoine Griezmann', 'Kylian Mbappé', 'Ousmane Dembélé', 'Marcus Thuram', 'Bradley Barcola',
    'Randal Kolo Muani', 'Kingsley Coman', 'Olivier Giroud',
  ],
  'Senegal': [
    'Édouard Mendy', 'Alfred Gomis', 'Seny Dieng',
    'Kalidou Koulibaly', 'Abdou Diallo', 'Youssouf Sabaly', 'Fodé Ballo-Touré', 'Formose Mendy',
    'Cheikhou Kouyaté', 'Idrissa Gueye', 'Pape Gueye', 'Nampalys Mendy', 'Pathé Ciss',
    'Ismaïla Sarr', 'Sadio Mané', 'Habib Diallo', 'Nicolas Jackson', 'Krepin Diatta',
    'Bamba Dieng', 'Famara Diédhiou',
  ],
  'Iraq': [
    'Jalal Hassan', 'Mohammed Hameed', 'Ahmed Basil',
    'Saman Khadr', 'Ali Adnan', 'Amjed Attwan', 'Ahmed Ibrahim', 'Saif Ghanim', 'Bassam Ali',
    'Bashar Resan', 'Safaa Hadi', 'Mohanad Ali', 'Hammadi Ahmed', 'Ali Fadhal', 'Humam Tariq',
    'Ayman Hussein', 'Alaa Abdul-Zahra', 'Manaf Yusuf', 'Ali Hassan', 'Moatasem Imad',
  ],
  'Norway': [
    'Ørjan Nyland', 'Rune Jarstein', 'Kristoffer Klaesson',
    'Stefan Strandberg', 'Leo Skiri Østigård', 'Julian Ryerson', 'Birger Meling', 'Martin Linnes', 'Andreas Hanche-Olsen',
    'Martin Ødegaard', 'Sander Berge', 'Mathias Normann', 'Fredrik Aursnes', 'Morten Thorsby',
    'Erling Haaland', 'Alexander Sørloth', 'Antonio Nusa', 'Jørgen Strand Larsen',
    'Mohammed Elyounoussi', 'Ola Solbakken',
  ],
  'Argentina': [
    'Emiliano Martínez', 'Franco Armani', 'Geronimo Rulli',
    'Nahuel Molina', 'Gonzalo Montiel', 'Cristian Romero', 'Lisandro Martínez', 'Marcos Acuña', 'Nicolás Tagliafico',
    'Rodrigo De Paul', 'Enzo Fernández', 'Leandro Paredes', 'Alexis Mac Allister', 'Giovani Lo Celso',
    'Lionel Messi', 'Lautaro Martínez', 'Julián Álvarez', 'Paulo Dybala', 'Nicolás González',
    'Ángel Di María', 'Thiago Almada', 'Valentín Carboni',
  ],
  'Algeria': [
    'Raïs M\'Bolhi', 'Alexandre Oukidja', 'Farouk Chafai',
    'Ramy Bensebaini', 'Aïssa Mandi', 'Djamel Benlamri', 'Youcef Atal', 'Abdelkader Bedrane',
    'Nabil Bentaleb', 'Ismaël Bennacer', 'Sofiane Feghouli', 'Houssem Aouar', 'Said Benrahma', 'Farid Boulaya',
    'Riyad Mahrez', 'Youcef Belaïli', 'Baghdad Bounedjah', 'Andy Delort', 'Islam Slimani',
  ],
  'Austria': [
    'Patrick Pentz', 'Heinz Lindner', 'Daniel Bachmann',
    'David Alaba', 'Maximilian Wöber', 'Phillipp Lienhart', 'Stefan Posch', 'Aleksandar Dragović', 'Philipp Mwene',
    'Marcel Sabitzer', 'Konrad Laimer', 'Xaver Schlager', 'Nicolas Seiwald', 'Florian Grillitsch',
    'Christoph Baumgartner', 'Marko Arnautović', 'Michael Gregoritsch', 'Sasa Kalajdzic',
    'Patrick Wimmer', 'Junior Adamu',
  ],
  'Jordan': [
    'Yazeed Abo Laila', 'Amer Shafi', 'Mohammed Al-Salfiti',
    'Yazan Al-Arab', 'Edis Resulović', 'Ahmad Ibrahim Hayel', 'Baha Faisal', 'Oday Dabbagh',
    'Noor Al-Rawabdeh', 'Hamza Al-Dardour', 'Yazan Al-Naimat', 'Ahmad Burqan', 'Ziad Al-Bakkar',
    'Musa Al-Taamari', 'Feras Ibrahim', 'Mahmoud Almardi', 'Mohammad Abu Zema',
  ],
  'Portugal': [
    'Rui Patrício', 'Diogo Costa', 'José Sá',
    'João Cancelo', 'Rúben Dias', 'Pepe', 'Nuno Mendes', 'Danilo Pereira', 'António Silva', 'Gonçalo Inácio',
    'Bruno Fernandes', 'Bernardo Silva', 'Vitinha', 'João Palhinha', 'Rúben Neves', 'Otávio',
    'Gonçalo Ramos', 'Rafael Leão', 'Diogo Jota', 'Cristiano Ronaldo', 'Pedro Neto', 'João Félix',
  ],
  'DR Congo': [
    'Joël Kiassumbua', 'Parfait Mandanda', 'Ley Matampi',
    'Arthur Masuaku', 'Chancel Mbemba', 'Christian Luyindama', 'Marcel Tisserand', 'Merveille Bope Lukeba',
    'Neeskens Kebano', 'Théo Bongonda', 'Meschack Elia', 'Gaël Kakuta', 'Cédric Bakambu',
    'Yoane Wissa', 'Jackson Muleka', 'Silas', 'Jonathan Bolingi', 'Dieumerci Mbokani',
  ],
  'England': [
    'Jordan Pickford', 'Nick Pope', 'Aaron Ramsdale',
    'Trent Alexander-Arnold', 'Reece James', 'Kyle Walker', 'Ben White', 'John Stones', 'Marc Guéhi', 'Luke Shaw',
    'Declan Rice', 'Jude Bellingham', 'Phil Foden', 'Conor Gallagher', 'Adam Wharton',
    'Harry Kane', 'Bukayo Saka', 'Raheem Sterling', 'Marcus Rashford', 'Jack Grealish',
    'Ollie Watkins', 'Jarrod Bowen', 'Anthony Gordon', 'Cole Palmer',
  ],
  'Croatia': [
    'Dominik Livaković', 'Ivica Ivušić', 'Nediljko Labrović',
    'Joško Gvardiol', 'Dejan Lovren', 'Sime Vrsaljko', 'Domagoj Vida', 'Borna Sosa', 'Josip Stanišić',
    'Luka Modrić', 'Mateo Kovačić', 'Marcelo Brozović', 'Lovro Majer', 'Mario Pašalić', 'Kristijan Jakić',
    'Ivan Perišić', 'Andrej Kramarić', 'Marko Livaja', 'Bruno Petković', 'Mislav Oršić', 'Nikola Vlašić',
  ],
  'Ghana': [
    'Richard Ofori', 'Abdul Manaf Nurudeen', 'Lawrence Ati-Zigi',
    'Joseph Aidoo', 'Daniel Amartey', 'Gideon Mensah', 'Alexander Djiku', 'Baba Rahman', 'Tariq Lamptey',
    'Thomas Partey', 'Mubarak Wakaso', 'Elisha Owusu', 'Mohammed Kudus', 'Daniel Kofi Kyereh',
    'Jordan Ayew', 'André Ayew', 'Osman Bukari', 'Antoine Semenyo', 'Iñaki Williams',
    'Kamaldeen Sulemana', 'Felix Afena-Gyan',
  ],
  'Panama': [
    'Luis Mejía', 'Orlando Mosquera', 'José Calderón',
    'Harold Cummings', 'Éric Davis', 'Fidel Escobar', 'César Yanis', 'Rodolfo Austin', 'José Córdoba',
    'Armando Cooper', 'Alberto Quintero', 'Adalberto Carrasquilla', 'Cristian Martínez', 'Ricardo Clark',
    'Cecilio Waterman', 'Gabriel Torres', 'Ismael Díaz', 'Édgar Bárcenas', 'Iván Anderson', 'René Blackburn',
  ],
  'Uzbekistan': [
    'Utkir Yusupov', 'Sarvarbek Tursunov',
    'Otabek Shukurov', 'Shorukh Abdukholiqov', 'Eldorbek Sobirov', 'Jasur Yaxshiboev', 'Husan Kholmatov',
    'Jaloliddin Masharipov', 'Abbosbek Fayzullayev', 'Husain Norchaev', 'Jamshid Iskanderov', 'Hojimat Erziyev',
    'Eldor Shomurodov', 'Bobur Abdixoliqov', 'Dostonbek Khamdamov', 'Umid Nortojiev', 'Akbar Tursunov',
  ],
  'Colombia': [
    'David Ospina', 'Camilo Vargas', 'Kevin Mier',
    'Dávinson Sánchez', 'Jhon Lucumí', 'Daniel Muñoz', 'Johan Mojica', 'Carlos Cuesta', 'Santiago Arias',
    'Wilmar Barrios', 'Matheus Uribe', 'James Rodríguez', 'Richard Ríos', 'Gustavo Cuéllar',
    'Luis Díaz', 'Rafael Santos Borré', 'Miguel Ángel Borja', 'Jhon Córdoba', 'Cucho Hernández',
    'Jhon Durán', 'Juan Cuadrado',
  ],
  'Czechia': [
    'Jindřich Staněk', 'Matěj Kovář', 'Vítězslav Jaroš',
    'Vladimír Coufal', 'Tomáš Holeš', 'Robin Hranáč', 'David Zima', 'Ladislav Krejčí', 'David Doudera',
    'Tomáš Souček', 'Lukáš Provod', 'Antonín Barák', 'Pavel Šulc', 'Michal Sadílek', 'Lukáš Červ',
    'Adam Hložek', 'Patrik Schick', 'Mojmír Chytil', 'Tomáš Chorý', 'Václav Černý', 'Ondřej Lingr',
  ],
  'South Africa': [
    'Ronwen Williams', 'Ricardo Goss', 'Sipho Chaine',
    'Khuliso Mudau', 'Nyiko Mobbie', 'Mothobi Mvala', 'Siyanda Xulu', 'Aubrey Modiba', 'Terrence Mashego',
    'Teboho Mokoena', 'Sphephelo Sithole', 'Bongokuhle Hlongwane', 'Themba Zwane', 'Thalente Mbatha',
    'Percy Tau', 'Lyle Foster', 'Iqraam Rayners', 'Evidence Makgopa', 'Mihlali Mayambela', 'Oswin Appollis',
  ],
  'Switzerland': [
    'Yann Sommer', 'Gregor Kobel', 'Yvon Mvogo',
    'Manuel Akanji', 'Nico Elvedi', 'Ricardo Rodríguez', 'Fabian Schär', 'Silvan Widmer', 'Aurèle Amenda',
    'Granit Xhaka', 'Remo Freuler', 'Denis Zakaria', 'Michel Aebischer', 'Fabian Rieder', 'Ardon Jashari',
    'Xherdan Shaqiri', 'Breel Embolo', 'Ruben Vargas', 'Dan Ndoye', 'Zeki Amdouni', 'Steven Zuber',
  ],
  'Bosnia and Herzegovina': [
    'Nikola Vasilj', 'Ibrahim Šehić', 'Vladan Kovačević',
    'Sead Kolašinac', 'Amar Dedić', 'Nihad Mujakić', 'Dennis Hadžikadunić', 'Adnan Kovačević', 'Eldar Ćivić',
    'Miralem Pjanić', 'Edin Višća', 'Benjamin Tahirović', 'Gojko Cimirot', 'Amar Memić',
    'Edin Džeko', 'Ermedin Demirović', 'Smail Prevljak', 'Haris Tabaković', 'Said Hamulić', 'Armin Gigović',
  ],
  'Canada': [
    'Maxime Crépeau', 'Dayne St. Clair', 'Milan Borjan',
    'Alphonso Davies', 'Alistair Johnston', 'Moïse Bombito', 'Derek Cornelius', 'Kamal Miller', 'Richie Laryea',
    'Stephen Eustáquio', 'Ismaël Koné', 'Jonathan Osorio', 'Mathieu Choinière', 'Liam Fraser',
    'Jonathan David', 'Cyle Larin', 'Tajon Buchanan', 'Jacob Shaffelburg', 'Promise David', 'Ali Ahmed',
  ],
  'Qatar': [
    'Meshaal Barsham', 'Saad Al Sheeb', 'Yousef Hassan',
    'Pedro Miguel', 'Boualem Khoukhi', 'Tarek Salman', 'Bassam Al-Rawi', 'Homam Ahmed', 'Sultan Al-Brake',
    'Karim Boudiaf', 'Hassan Al-Haydos', 'Abdulaziz Hatem', 'Mohammed Waad', 'Jassem Gaber', 'Ahmed Fathi',
    'Akram Afif', 'Almoez Ali', 'Yusuf Abdurisag', 'Ismaeel Mohammad', 'Mohammed Muntari', 'Khalid Muneer',
  ],
  'Mexico': [
    'Guillermo Ochoa', 'Luis Malagón', 'Julio González',
    'Jorge Sánchez', 'César Montes', 'Johan Vásquez', 'Israel Reyes', 'Jesús Gallardo', 'Gerardo Arteaga',
    'Edson Álvarez', 'Luis Chávez', 'Carlos Rodríguez', 'Orbelín Pineda', 'Luis Romo', 'Érick Sánchez',
    'Hirving Lozano', 'Santiago Giménez', 'Raúl Jiménez', 'Alexis Vega', 'Uriel Antuna', 'Roberto Alvarado',
  ],
  'South Korea': [
    'Kim Seung-gyu', 'Jo Hyeon-woo', 'Song Bum-keun',
    'Kim Min-jae', 'Kim Young-gwon', 'Kim Ji-soo', 'Kim Moon-hwan', 'Lee Ki-je', 'Seol Young-woo',
    'Hwang In-beom', 'Lee Jae-sung', 'Park Yong-woo', 'Hong Hyun-seok', 'Won Du-jae', 'Jung Woo-yeong',
    'Son Heung-min', 'Hwang Hee-chan', 'Lee Kang-in', 'Oh Hyeon-gyu', 'Cho Gue-sung', 'Jeon Jin-woo',
  ],
};
